#!/bin/bash

env_vars=("EXECUTION_BOOTNODE_START_IP_ADDR" "NETRESTRICT_RANGE" "EXECUTION_BOOTNODE_DISC_PORT" "EXECUTION_BOOTNODE_PRIVATE_KEY" "EXECUTION_BOOTNODE_VERBOSITY" "EXECUTION_BOOTNODE_ENODE" "EXECUTION_BOOTNODE_ENODE_FILE" "EXECUTION_BOOTNODE_ENODE_DIR")

for var in "${env_vars[@]}" ; do
    if [[ -z "${!var}" ]]; then
        echo "$var not set"
        exit 1
    fi
done

mkdir -p $EXECUTION_BOOTNODE_ENODE_DIR

echo "Starting geth-bootnode"
echo "$EXECUTION_BOOTNODE_ENODE@$EXECUTION_BOOTNODE_START_IP_ADDR?discport=$EXECUTION_BOOTNODE_DISC_PORT" > $EXECUTION_BOOTNODE_ENODE_FILE


geth \
    -nodekeyhex "$EXECUTION_BOOTNODE_PRIVATE_KEY" \
    -nat "extip:$EXECUTION_BOOTNODE_START_IP_ADDR" \
    -addr ":$EXECUTION_BOOTNODE_DISC_PORT" \
